//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWeakestRival.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessages
    {
        public int chat_message_id { get; set; }
        public int user_id { get; set; }
        public string display_name { get; set; }
        public string message_text { get; set; }
        public System.DateTime sent_utc { get; set; }
        public Nullable<int> lobby_id { get; set; }
    
        public virtual Lobbies Lobbies { get; set; }
    }
}
