//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWeakestRival.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailVerifications
    {
        public int verification_id { get; set; }
        public string email { get; set; }
        public byte[] code_hash { get; set; }
        public System.DateTime expires_at_utc { get; set; }
        public bool used { get; set; }
        public System.DateTime created_at_utc { get; set; }
        public Nullable<System.DateTime> used_at_utc { get; set; }
        public byte attempts { get; set; }
    }
}
