//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWeakestRival.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LobbyMembers
    {
        public int lobby_id { get; set; }
        public int user_id { get; set; }
        public byte role { get; set; }
        public System.DateTime joined_at_utc { get; set; }
        public Nullable<System.DateTime> left_at_utc { get; set; }
        public bool is_active { get; set; }
    
        public virtual Lobbies Lobbies { get; set; }
        public virtual Users Users { get; set; }
    }
}
