//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWeakestRival.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lobbies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lobbies()
        {
            this.ChatMessages = new HashSet<ChatMessages>();
            this.LobbyMembers = new HashSet<LobbyMembers>();
        }
    
        public int lobby_id { get; set; }
        public int owner_user_id { get; set; }
        public string access_code { get; set; }
        public string name { get; set; }
        public byte status { get; set; }
        public byte max_players { get; set; }
        public System.DateTime created_at_utc { get; set; }
        public Nullable<System.DateTime> closed_at_utc { get; set; }
        public System.Guid lobby_uid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMessages> ChatMessages { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LobbyMembers> LobbyMembers { get; set; }
    }
}
