//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWeakestRival.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchRules
    {
        public int match_id { get; set; }
        public decimal starting_score { get; set; }
        public decimal max_score { get; set; }
        public decimal points_per_correct { get; set; }
        public decimal points_per_wrong { get; set; }
        public decimal points_per_elimination_gain { get; set; }
        public bool allow_tiebreak_coinflip { get; set; }
    
        public virtual Matches Matches { get; set; }
    }
}
