//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWeakestRival.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheWeakestRivalEntities : DbContext
    {
        public TheWeakestRivalEntities()
            : base("name=TheWeakestRivalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Eliminations> Eliminations { get; set; }
        public virtual DbSet<FriendRequests> FriendRequests { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<MatchInvitations> MatchInvitations { get; set; }
        public virtual DbSet<MatchPlayers> MatchPlayers { get; set; }
        public virtual DbSet<MatchReactions> MatchReactions { get; set; }
        public virtual DbSet<MatchRules> MatchRules { get; set; }
        public virtual DbSet<PlayerWildcards> PlayerWildcards { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<ReactionTypes> ReactionTypes { get; set; }
        public virtual DbSet<RoundQuestions> RoundQuestions { get; set; }
        public virtual DbSet<Rounds> Rounds { get; set; }
        public virtual DbSet<RoundVotes> RoundVotes { get; set; }
        public virtual DbSet<UserFriends> UserFriends { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WildcardTypes> WildcardTypes { get; set; }
    }
}
