//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWeakestRival.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordResetRequests
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public byte[] CodeHash { get; set; }
        public System.DateTime ExpiresAtUtc { get; set; }
        public bool Used { get; set; }
        public int Attempts { get; set; }
        public System.DateTime CreatedAtUtc { get; set; }
    }
}
