//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TheWeakestRival.Data
{
    using System;
    using System.Collections.Generic;

    public partial class Users
    {
        public Users()
        {
            this.Eliminations = new HashSet<Eliminations>();
            this.Eliminations1 = new HashSet<Eliminations>();
            this.FriendRequests = new HashSet<FriendRequests>();
            this.FriendRequests1 = new HashSet<FriendRequests>();
            this.Matches = new HashSet<Matches>();
            this.MatchInvitations = new HashSet<MatchInvitations>();
            this.MatchInvitations1 = new HashSet<MatchInvitations>();
            this.MatchPlayers = new HashSet<MatchPlayers>();
            this.MatchReactions = new HashSet<MatchReactions>();
            this.MatchReactions1 = new HashSet<MatchReactions>();
            this.PlayerWildcards = new HashSet<PlayerWildcards>();
            this.Questions = new HashSet<Questions>();
            this.RoundQuestions = new HashSet<RoundQuestions>();
            this.RoundVotes = new HashSet<RoundVotes>();
            this.RoundVotes1 = new HashSet<RoundVotes>();
            this.UserFriends = new HashSet<UserFriends>();
            this.UserFriends1 = new HashSet<UserFriends>();
            this.Lobbies = new HashSet<Lobbies>();
            this.LobbyMembers = new HashSet<LobbyMembers>();
        }

        public int user_id { get; set; }
        public string display_name { get; set; }

        public byte[] profile_image { get; set; }
        public string profile_image_content_type { get; set; }

        public System.DateTime created_at { get; set; }

        public virtual Accounts Accounts { get; set; }
        public virtual ICollection<Eliminations> Eliminations { get; set; }
        public virtual ICollection<Eliminations> Eliminations1 { get; set; }
        public virtual ICollection<FriendRequests> FriendRequests { get; set; }
        public virtual ICollection<FriendRequests> FriendRequests1 { get; set; }
        public virtual ICollection<Matches> Matches { get; set; }
        public virtual ICollection<MatchInvitations> MatchInvitations { get; set; }
        public virtual ICollection<MatchInvitations> MatchInvitations1 { get; set; }
        public virtual ICollection<MatchPlayers> MatchPlayers { get; set; }
        public virtual ICollection<MatchReactions> MatchReactions { get; set; }
        public virtual ICollection<MatchReactions> MatchReactions1 { get; set; }
        public virtual ICollection<PlayerWildcards> PlayerWildcards { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual ICollection<RoundQuestions> RoundQuestions { get; set; }
        public virtual ICollection<RoundVotes> RoundVotes { get; set; }
        public virtual ICollection<RoundVotes> RoundVotes1 { get; set; }
        public virtual ICollection<UserFriends> UserFriends { get; set; }
        public virtual ICollection<UserFriends> UserFriends1 { get; set; }
        public virtual ICollection<Lobbies> Lobbies { get; set; }
        public virtual ICollection<LobbyMembers> LobbyMembers { get; set; }
        public virtual UserPresence UserPresence { get; set; }
    }
}
