//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWeakestRival.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFriends
    {
        public int user_id { get; set; }
        public int friend_user_id { get; set; }
        public System.DateTime since_at { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
