//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int account_id { get; set; }
        public string email { get; set; }
        public byte[] password_hash { get; set; }
        public byte status { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
