//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int answer_id { get; set; }
        public int question_id { get; set; }
        public string answer_text { get; set; }
        public bool is_correct { get; set; }
        public byte display_ord { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
