//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eliminations
    {
        public int elimination_id { get; set; }
        public int round_id { get; set; }
        public int eliminated_user_id { get; set; }
        public string reason { get; set; }
        public bool tiebreak_used { get; set; }
        public string tiebreak_method { get; set; }
        public Nullable<int> decided_by_user_id { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Rounds Rounds { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
