//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchReactions
    {
        public int reaction_id { get; set; }
        public int match_id { get; set; }
        public int from_user_id { get; set; }
        public Nullable<int> to_user_id { get; set; }
        public Nullable<int> round_id { get; set; }
        public int reaction_type_id { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Matches Matches { get; set; }
        public virtual Users Users { get; set; }
        public virtual Rounds Rounds { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ReactionTypes ReactionTypes { get; set; }
    }
}
