//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchInvitations
    {
        public int invitation_id { get; set; }
        public int match_id { get; set; }
        public int from_user_id { get; set; }
        public int to_user_id { get; set; }
        public byte status { get; set; }
        public System.DateTime sent_at { get; set; }
        public Nullable<System.DateTime> responded_at { get; set; }
    
        public virtual Matches Matches { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
