//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerWildcards
    {
        public int player_wildcard_id { get; set; }
        public int match_id { get; set; }
        public int user_id { get; set; }
        public int wildcard_type_id { get; set; }
        public System.DateTime granted_at { get; set; }
        public Nullable<System.DateTime> consumed_at { get; set; }
        public Nullable<int> consumed_in_round { get; set; }
    
        public virtual Matches Matches { get; set; }
        public virtual Rounds Rounds { get; set; }
        public virtual WildcardTypes WildcardTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
