//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundQuestions
    {
        public int round_question_id { get; set; }
        public int round_id { get; set; }
        public int question_id { get; set; }
        public int assigned_to_user { get; set; }
        public Nullable<System.DateTime> answered_at { get; set; }
        public Nullable<bool> is_correct { get; set; }
        public Nullable<int> response_ms { get; set; }
        public Nullable<decimal> points_awarded { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Rounds Rounds { get; set; }
        public virtual Users Users { get; set; }
    }
}
