//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundVotes
    {
        public int round_id { get; set; }
        public int voter_user_id { get; set; }
        public int voted_user_id { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Rounds Rounds { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
